# Generate output/diagnosis_sw.csv (IN / group1) and diagnosis_sw_group2.csv (OUT / SW1 swap).
# Mapping verified against samples CH163, CH343, CH378, etc.
# Runtime IL Test builds SW from IlTestBuildSwCommandsForChannelHalf; group2 CSV is reference only.
from __future__ import print_function
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "output")
DIST_OUT = os.path.join(SCRIPT_DIR, "..", "dist", "M576Calibrator", "output")

HEADER_G1 = r"""# Diagnosis input CSV. One *group* per data line.
# AUTO-GENERATED by tools/generate_diagnosis_sw_576.py - 32x18 MCS grid (576 channels).
# IL Test IN half (odd lap). OUT half uses SW1 port swap (see diagnosis_sw_group2.csv).
#
# Channel label: CH{k} where k = (sw-1)*18 + ch, sw=1..32, ch=1..18.
# SW commands per group (IN):
#   SW 1 1 {sw}|SW 1 2 {sw+32}|SW 2 {sw} {ch}|SW 2 {sw+32} {ch}
# (1#1x64 port sw, 2#1x64 port sw+32; same channel on both 1x18 switches.)
#
# Format:
#   - Each data line is one logical diagnosis step:
#       <SW cmd 1>|<SW cmd 2>|...|<SW cmd N>
#     The host sends every SW command in order (CR appended automatically),
#     reads one reply line per SW (typically "OK"/"FAIL").
#   - After all SW in the group, the host runs three measure paths (s1/s2/s3), no precheck:
#         (1) SFP_1550:  SW 3 1 1,  SWL 8 1550, pd 1, opm 3 1
#         (2) SFP_1310:  SW 3 1 4,  SWL 8 1310, pd 1, opm 3 1
#         (3) Laser_1310: SW 3 1 8, SWL 8 1310, pd 1, opm 3 1
#   - Tokens are separated by '|'. Whitespace around tokens is trimmed.
#   - Lines starting with '#' or ';' are comments. The trimmed text after
#     the marker is attached as the *label* of the next data line (used for
#     reporting only; not sent over serial).
#   - UTF-8 BOM on the first line is tolerated.
#
# Result log (append): output\diagnosis_log.csv - 7 columns (see diagnosis_sw.csv.example).
#   If the log has an older header (e.g. 25-column precheck format), delete or rename output\diagnosis_log.csv once.

"""

HEADER_G2 = r"""# Reference CSV for IL Test OUT half (even lap) — SW1 1x64 ports swapped.
# AUTO-GENERATED by tools/generate_diagnosis_sw_576.py. Host does NOT load this at runtime;
# IlTestBuildSwCommandsForChannelHalf(half=2) emits the same wires.
#
# Channel label: CH{k} where k = (sw-1)*18 + ch, sw=1..32, ch=1..18.
# SW commands per group (OUT):
#   SW 1 1 {sw+32}|SW 1 2 {sw}|SW 2 {sw} {ch}|SW 2 {sw+32} {ch}
# (SW1 ports swapped vs diagnosis_sw.csv; SW2 unchanged.)
#
# Tokens separated by '|'. Comment lines starting with '#' attach label to next data line.

"""


def row_for(sw, ch, group2=False):
    k = (sw - 1) * 18 + ch
    pa = sw
    pb = sw + 32
    if group2:
        sw_line = "SW 1 1 %d|SW 1 2 %d|SW 2 %d %d|SW 2 %d %d" % (pb, pa, pa, ch, pb, ch)
    else:
        sw_line = "SW 1 1 %d|SW 1 2 %d|SW 2 %d %d|SW 2 %d %d" % (pa, pb, pa, ch, pb, ch)
    return k, sw_line


def write_csv(path, header, group2):
    lines = [header]
    for sw in range(1, 33):
        for ch in range(1, 19):
            k, sw_line = row_for(sw, ch, group2=group2)
            lines.append("# CH%d\n" % k)
            lines.append(sw_line + "\n")
            lines.append("\n")
    body = "".join(lines)
    out_dir = os.path.dirname(path)
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    with open(path, "wb") as f:
        f.write(body.encode("utf-8"))
    print("Wrote %d channel groups -> %s" % (32 * 18, path))


def main():
    targets = [
        (os.path.join(OUT_DIR, "diagnosis_sw.csv"), HEADER_G1, False),
        (os.path.join(OUT_DIR, "diagnosis_sw_group2.csv"), HEADER_G2, True),
        (os.path.join(DIST_OUT, "diagnosis_sw.csv"), HEADER_G1, False),
        (os.path.join(DIST_OUT, "diagnosis_sw_group2.csv"), HEADER_G2, True),
    ]
    for path, header, g2 in targets:
        write_csv(path, header, g2)


if __name__ == "__main__":
    main()
