# Generate output/diagnosis_sw.csv for Run Diagnosis (576 MCS grid channels).
# Mapping verified against samples CH163, CH343, CH378, etc.
from __future__ import print_function
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATHS = [
    os.path.join(SCRIPT_DIR, "..", "output", "diagnosis_sw.csv"),
    os.path.join(SCRIPT_DIR, "..", "dist", "M576Calibrator", "output", "diagnosis_sw.csv"),
]

HEADER = r"""# Diagnosis input CSV. One *group* per data line.
# AUTO-GENERATED by tools/generate_diagnosis_sw_576.py - 32x18 MCS grid (576 channels).
#
# Channel label: CH{k} where k = (sw-1)*18 + ch, sw=1..32, ch=1..18.
# SW commands per group:
#   SW 1 1 {sw}|SW 1 2 {sw+32}|SW 2 {sw} {ch}|SW 2 {sw+32} {ch}
# (1#1x64 port sw, 2#1x64 port sw+32; same channel on both 1x18 switches.)
#
# Format:
#   - Each data line is one logical diagnosis step:
#       <SW cmd 1>|<SW cmd 2>|...|<SW cmd N>
#     The host sends every SW command in order (CR appended automatically),
#     reads one reply line per SW (typically "OK"/"FAIL").
#   - After all SW in the group, the host runs three measure paths (s1/s2/s3), no precheck:
#         (1) SFP_1550:  SW 3 1 1,  SWL 8 1550, pd 1, opm 3 1
#         (2) SFP_1310:  SW 3 1 4,  SWL 8 1310, pd 1, opm 3 1
#         (3) Laser_1310: SW 3 1 8, SWL 8 1310, pd 1, opm 3 1
#   - Tokens are separated by '|'. Whitespace around tokens is trimmed.
#   - Lines starting with '#' or ';' are comments. The trimmed text after
#     the marker is attached as the *label* of the next data line (used for
#     reporting only; not sent over serial).
#   - UTF-8 BOM on the first line is tolerated.
#
# Result log (append): output\diagnosis_log.csv - 7 columns (see diagnosis_sw.csv.example).
#   If the log has an older header (e.g. 25-column precheck format), delete or rename output\diagnosis_log.csv once.

"""


def row_for(sw, ch):
    k = (sw - 1) * 18 + ch
    pa = sw
    pb = sw + 32
    sw_line = "SW 1 1 %d|SW 1 2 %d|SW 2 %d %d|SW 2 %d %d" % (pa, pb, pa, ch, pb, ch)
    return k, sw_line


def main():
    lines = [HEADER]
    for sw in range(1, 33):
        for ch in range(1, 19):
            k, sw_line = row_for(sw, ch)
            lines.append("# CH%d\n" % k)
            lines.append(sw_line + "\n")
            lines.append("\n")

    body = "".join(lines)
    for path in OUT_PATHS:
        out_dir = os.path.dirname(path)
        if not os.path.isdir(out_dir):
            os.makedirs(out_dir)
        with open(path, "wb") as f:
            f.write(body.encode("utf-8"))
        print("Wrote %d channel groups -> %s" % (32 * 18, path))


if __name__ == "__main__":
    main()
