// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ntgraph1.h"

// Dispatch interfaces referenced by this interface
#include "font.h"
#include "Picture.h"

/////////////////////////////////////////////////////////////////////////////
// CNTGraph1

IMPLEMENT_DYNCREATE(CNTGraph1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNTGraph1 properties

short CNTGraph1::GetAppearance()
{
	short result;
	GetProperty(DISPID_APPEARANCE, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetAppearance(short propVal)
{
	SetProperty(DISPID_APPEARANCE, VT_I2, propVal);
}

CString CNTGraph1::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

BOOL CNTGraph1::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

unsigned long CNTGraph1::GetAxisColor()
{
	unsigned long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetAxisColor(unsigned long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

unsigned long CNTGraph1::GetGridColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetGridColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CNTGraph1::GetLabelColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetLabelColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

unsigned long CNTGraph1::GetCursorColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

COleFont CNTGraph1::GetLabelFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2b, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CNTGraph1::SetLabelFont(LPDISPATCH propVal)
{
	SetProperty(0x2b, VT_DISPATCH, propVal);
}

COleFont CNTGraph1::GetTickFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2c, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CNTGraph1::SetTickFont(LPDISPATCH propVal)
{
	SetProperty(0x2c, VT_DISPATCH, propVal);
}

COleFont CNTGraph1::GetTitleFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2d, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CNTGraph1::SetTitleFont(LPDISPATCH propVal)
{
	SetProperty(0x2d, VT_DISPATCH, propVal);
}

COleFont CNTGraph1::GetIdentFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2e, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CNTGraph1::SetIdentFont(LPDISPATCH propVal)
{
	SetProperty(0x2e, VT_DISPATCH, propVal);
}

short CNTGraph1::GetXGridNumber()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetXGridNumber(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

short CNTGraph1::GetYGridNumber()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetYGridNumber(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

BOOL CNTGraph1::GetShowGrid()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetShowGrid(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

CString CNTGraph1::GetXLabel()
{
	CString result;
	GetProperty(0x8, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetXLabel(LPCTSTR propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}

CString CNTGraph1::GetYLabel()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetYLabel(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

unsigned long CNTGraph1::GetElementLineColor()
{
	unsigned long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetElementLineColor(unsigned long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

unsigned long CNTGraph1::GetElementPointColor()
{
	unsigned long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetElementPointColor(unsigned long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

long CNTGraph1::GetElementLinetype()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetElementLinetype(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

long CNTGraph1::GetElementWidth()
{
	long result;
	GetProperty(0xd, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetElementWidth(long propVal)
{
	SetProperty(0xd, VT_I4, propVal);
}

long CNTGraph1::GetElementPointSymbol()
{
	long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetElementPointSymbol(long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

BOOL CNTGraph1::GetElementSolidPoint()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetElementSolidPoint(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

BOOL CNTGraph1::GetElementShow()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetElementShow(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

long CNTGraph1::GetTrackMode()
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetTrackMode(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

CString CNTGraph1::GetElementName()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetElementName(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

BOOL CNTGraph1::GetElementIdentify()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetElementIdentify(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

BOOL CNTGraph1::GetXLog()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetXLog(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

BOOL CNTGraph1::GetYLog()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetYLog(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

CPicture CNTGraph1::GetControlFramePicture()
{
	LPDISPATCH pDispatch;
	GetProperty(0x30, VT_DISPATCH, (void*)&pDispatch);
	return CPicture(pDispatch);
}

void CNTGraph1::SetControlFramePicture(LPDISPATCH propVal)
{
	SetProperty(0x30, VT_DISPATCH, propVal);
}

CPicture CNTGraph1::GetPlotAreaPicture()
{
	LPDISPATCH pDispatch;
	GetProperty(0x31, VT_DISPATCH, (void*)&pDispatch);
	return CPicture(pDispatch);
}

void CNTGraph1::SetPlotAreaPicture(LPDISPATCH propVal)
{
	SetProperty(0x31, VT_DISPATCH, propVal);
}

unsigned long CNTGraph1::GetControlFrameColor()
{
	unsigned long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetControlFrameColor(unsigned long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

unsigned long CNTGraph1::GetPlotAreaColor()
{
	unsigned long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetPlotAreaColor(unsigned long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

long CNTGraph1::GetFrameStyle()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetFrameStyle(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

CString CNTGraph1::GetAnnoLabelCaption()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoLabelCaption(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

double CNTGraph1::GetAnnoLabelX()
{
	double result;
	GetProperty(0x19, VT_R8, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoLabelX(double propVal)
{
	SetProperty(0x19, VT_R8, propVal);
}

double CNTGraph1::GetAnnoLabelY()
{
	double result;
	GetProperty(0x1a, VT_R8, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoLabelY(double propVal)
{
	SetProperty(0x1a, VT_R8, propVal);
}

unsigned long CNTGraph1::GetAnnoLabelColor()
{
	unsigned long result;
	GetProperty(0x1b, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoLabelColor(unsigned long propVal)
{
	SetProperty(0x1b, VT_I4, propVal);
}

BOOL CNTGraph1::GetAnnoLabelHorizontal()
{
	BOOL result;
	GetProperty(0x1c, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoLabelHorizontal(BOOL propVal)
{
	SetProperty(0x1c, VT_BOOL, propVal);
}

short CNTGraph1::GetAnnotation()
{
	short result;
	GetProperty(0x1d, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnotation(short propVal)
{
	SetProperty(0x1d, VT_I2, propVal);
}

BOOL CNTGraph1::GetAnnoVisible()
{
	BOOL result;
	GetProperty(0x1e, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoVisible(BOOL propVal)
{
	SetProperty(0x1e, VT_BOOL, propVal);
}

short CNTGraph1::GetAnnoCount()
{
	short result;
	GetProperty(0x32, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoCount(short propVal)
{
	SetProperty(0x32, VT_I2, propVal);
}

short CNTGraph1::GetElement()
{
	short result;
	GetProperty(0x1f, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetElement(short propVal)
{
	SetProperty(0x1f, VT_I2, propVal);
}

short CNTGraph1::GetElementCount()
{
	short result;
	GetProperty(0x33, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetElementCount(short propVal)
{
	SetProperty(0x33, VT_I2, propVal);
}

unsigned long CNTGraph1::GetAnnoLabelBkColor()
{
	unsigned long result;
	GetProperty(0x20, VT_I4, (void*)&result);
	return result;
}

void CNTGraph1::SetAnnoLabelBkColor(unsigned long propVal)
{
	SetProperty(0x20, VT_I4, propVal);
}

short CNTGraph1::GetCursorCount()
{
	short result;
	GetProperty(0x34, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorCount(short propVal)
{
	SetProperty(0x34, VT_I2, propVal);
}

short CNTGraph1::GetCursor()
{
	short result;
	GetProperty(0x21, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetCursor(short propVal)
{
	SetProperty(0x21, VT_I2, propVal);
}

double CNTGraph1::GetCursorX()
{
	double result;
	GetProperty(0x22, VT_R8, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorX(double propVal)
{
	SetProperty(0x22, VT_R8, propVal);
}

double CNTGraph1::GetCursorY()
{
	double result;
	GetProperty(0x23, VT_R8, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorY(double propVal)
{
	SetProperty(0x23, VT_R8, propVal);
}

short CNTGraph1::GetCursorStyle()
{
	short result;
	GetProperty(0x24, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorStyle(short propVal)
{
	SetProperty(0x24, VT_I2, propVal);
}

BOOL CNTGraph1::GetCursorVisible()
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorVisible(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

short CNTGraph1::GetCursorMode()
{
	short result;
	GetProperty(0x26, VT_I2, (void*)&result);
	return result;
}

void CNTGraph1::SetCursorMode(short propVal)
{
	SetProperty(0x26, VT_I2, propVal);
}

CString CNTGraph1::GetFormatAxisBottom()
{
	CString result;
	GetProperty(0x27, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetFormatAxisBottom(LPCTSTR propVal)
{
	SetProperty(0x27, VT_BSTR, propVal);
}

CString CNTGraph1::GetFormatAxisLeft()
{
	CString result;
	GetProperty(0x28, VT_BSTR, (void*)&result);
	return result;
}

void CNTGraph1::SetFormatAxisLeft(LPCTSTR propVal)
{
	SetProperty(0x28, VT_BSTR, propVal);
}

BOOL CNTGraph1::GetYTime()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetYTime(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CNTGraph1::GetXTime()
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CNTGraph1::SetXTime(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNTGraph1 operations

void CNTGraph1::SetRange(double xmin, double xmax, double ymin, double ymax)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_R8 VTS_R8;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 xmin, xmax, ymin, ymax);
}

void CNTGraph1::AutoRange()
{
	InvokeHelper(0x36, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::CopyToClipboard()
{
	InvokeHelper(0x37, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::PrintGraph()
{
	InvokeHelper(0x38, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::AddElement()
{
	InvokeHelper(0x39, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::DeleteElement(short ElementID)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ElementID);
}

void CNTGraph1::ClearGraph()
{
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

double CNTGraph1::GetElementXValue(long index, short ElementID)
{
	double result;
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x44, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
		index, ElementID);
	return result;
}

void CNTGraph1::SetElementXValue(long index, short ElementID, double newValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_R8;
	InvokeHelper(0x44, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 index, ElementID, newValue);
}

double CNTGraph1::GetElementYValue(long index, short ElementID)
{
	double result;
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x45, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
		index, ElementID);
	return result;
}

void CNTGraph1::SetElementYValue(long index, short ElementID, double newValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_R8;
	InvokeHelper(0x45, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 index, ElementID, newValue);
}

void CNTGraph1::PlotXY(double X, double Y, short ElementID)
{
	static BYTE parms[] =
		VTS_R8 VTS_R8 VTS_I2;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 X, Y, ElementID);
}

void CNTGraph1::PlotY(double Y, short ElementID)
{
	static BYTE parms[] =
		VTS_R8 VTS_I2;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Y, ElementID);
}

void CNTGraph1::ShowProperties()
{
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::SaveAs(LPCTSTR szFilename)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szFilename);
}

void CNTGraph1::AddAnnotation()
{
	InvokeHelper(0x40, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::DeleteAnnotation(short annoID)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x41, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 annoID);
}

void CNTGraph1::AddCursor()
{
	InvokeHelper(0x42, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNTGraph1::DeleteCursor(short cursorID)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x43, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cursorID);
}

void CNTGraph1::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
