//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 126S_45V_Switch_App.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY126S_45V_SWITCH_APP_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SCAN                 129
#define IDD_DIALOG_R152_SET             129
#define IDD_DIALOG_SETTLS               130
#define IDD_DIALOG_SETSCAN              131
#define IDD_DIALOG_IP_R152              132
#define IDD_DIALOG_RL                   142
#define IDC_EDIT_ID                     1000
#define IDC_EDIT_SN                     1001
#define IDC_EDIT_SN2                    1002
#define IDC_EDIT_PN                     1003
#define IDC_BUTTON_IL_REF               1007
#define IDC_COMBO_CH2                   1007
#define IDC_COMBO_CH3                   1008
#define IDC_BUTTON_REPEAT               1008
#define IDC_BUTTON_RL_REF               1008
#define IDC_BUTTON_ILCT_TEST            1009
#define ID_SAVE_IP2                     1010
#define IDC_BUTTON_REPEAT_TEST          1010
#define IDC_BUTTON_SCAN_CH              1010
#define IDC_BUTTON_STOP_TEST            1011
#define ID_SAVE_IP3                     1011
#define IDC_COMBO_SEND_MESSAGE          1012
#define IDC_BUTTON6                     1013
#define IDC_BUTTON_ILCT_TEST2           1013
#define IDC_BUTTON_SCAN                 1014
#define IDC_BUTTON_ILCT_TEST3           1014
#define IDC_BUTTON_SW_CAL               1014
#define IDC_COMBO_CH_SET                1015
#define IDC_BUTTON10                    1016
#define IDC_BUTTON_SET_CHANNAL          1016
#define IDC_BUTTON_DOWNLoad             1016
#define IDC_BUTTON_PDL_TEST             1017
#define IDC_BUTTON_ILCT_TEST4           1017
#define IDC_BUTTON_WDL_TEST             1018
#define IDC_BUTTON_ILCT_TEST5           1018
#define IDC_BUTTON_TDL_TEST             1019
#define IDC_BUTTON_ILCT_TEST6           1019
#define IDC_COMBO_OPEN_PORT             1020
#define IDC_BUTTON_AUTOTEST             1020
#define IDC_COMBO_SET_WL                1020
#define IDC_BUTTON_OPEN_PORT            1021
#define IDC_COMBO_SET_PDBOX             1021
#define IDC_PROGRESS1                   1022
#define IDC_COMBO_SET_COMMAND           1022
#define IDC_BUTTON_OPEN_DEVICE          1022
#define IDC_LIST_INFO                   1023
#define IDC_IPADDRESS_IP1               1024
#define IDC_BUTTON_R152_SET             1024
#define IDC_BUTTON_CONNECT1830          1024
#define IDC_OPLINKGRAPHCTRL1            1025
#define IDC_IPADDRESS_IP2               1025
#define IDC_BUTTON_SAVE_DATA            1025
#define IDC_BUTTON_RL_TEST              1025
#define IDC_IPADDRESS_IP3               1026
#define IDC_COMBO_SaveData              1026
#define IDC_EDIT_WL1                    1027
#define IDC_COMBO_COMPORT               1027
#define IDC_BUTTON_SETWL1               1028
#define IDC_BUTTON_SWITCH_TIME          1028
#define IDC_COMBO_COMPORT2              1028
#define IDC_COMBO_TEMPNAME              1028
#define IDC_EDIT_WL2                    1029
#define IDC_BUTTON_WDL_REF              1029
#define IDC_BUTTON_SETWL2               1030
#define IDC_BUTTON_REPEAT_TEST2         1030
#define IDC_EDIT_WL3                    1031
#define IDC_BUTTON_DARK_TEST            1031
#define IDC_BUTTON_SETWL3               1032
#define IDC_BUTTON_UPDATE_ATMS          1032
#define IDC_BUTTON_ISO_TEST             1033
#define IDC_BUTTON_OPEN_TESTER_PORT     1034
#define IDC_BUTTON_SWITCH_ALL           1035
#define ID_SAVE_IP1                     1038
#define IDC_LIST_DATA2                  1039
#define IDC_LIST_DATA1                  1040
#define IDC_LIST_DATA3                  1041
#define IDC_COMBO_CH1                   1042
#define IDC_COMBO_SN_INDEX              1042
#define IDC_OP816XCTRL1                 1043
#define IDC_BUTTON_EXIT                 1044
#define IDC_BUTTON_SET_PM               1045
#define IDC_BUTTON_SaveIP1              1046
#define IDC_BUTTON_CLEAR                1046
#define IDC_IPADDRESS1                  1047
#define IDC_BUTTON_SaveIP2              1048
#define IDC_IPADDRESS2                  1049
#define IDC_BUTTON_READPOWER            1049
#define IDC_BUTTON_SaveIP3              1050
#define IDC_BUTTON_AUTO_TEST            1050
#define IDC_IPADDRESS3                  1051
#define IDC_BUTTON_SCAN_ZERO            1051
#define IDC_BUTTON_CONNECTIP            1052
#define IDC_BUTTON_SEND_MESSAGE         1053
#define IDC_EDIT_CHANNEL                1054
#define IDC_EDIT_X                      1055
#define IDC_EDIT_Y                      1056
#define IDC_EDIT_CHANNEL2               1057
#define IDC_EDIT_TLSWL                  1057
#define IDC_BUTTON_SET_CHANNEL_VOL      1058
#define IDC_EDIT_SET_VOA                1058
#define IDC_STATIC_CHANNEL              1059
#define IDC_STATIC_X                    1060
#define IDC_STATIC_Y                    1061
#define IDC_BUTTON_SET_VOLTAGE          1062
#define IDC_STATIC_PERIOD               1063
#define IDC_BUTTON_SET_TESTER_VOLTAGE   1063
#define IDC_NTGRAPHCTRL1                1064
#define IDC_STATIC_UNIT1                1065
#define IDC_STATIC_UNIT2                1066
#define IDC_EDIT_MESSAGE                1067
#define IDC_BUTTON_SET_WL               1067
#define IDC_BUTTON_TEST                 1068
#define IDC_BUTTON_SAVE_FILE            1069
#define IDC_BUTTON_SET_VOLTAGE2         1069
#define IDC_BUTTON_REGULATE_SCAN        1070
#define IDC_BUTTON_SINGLE_SCAN          1071
#define IDC_BUTTON_SET_VOLTAGE3         1071
#define IDC_BUTTON_SINGLE_SCAN2         1072
#define IDC_BUTTON_SINGLE_CHANNEL_SCAN  1072
#define IDC_BUTTON_REGULATE_SCAN2       1073
#define IDC_BUTTON_ZERO                 1076
#define IDC_COMBO_PN                    1077
#define IDC_EDIT_COM_PORT               1078
#define IDC_PROGRESS2                   1079
#define IDC_EDIT_PM_WL1                 1080
#define IDC_EDIT_COM_TESTER_PORT        1081
#define IDC_EDIT_PM_IL1                 1084
#define IDC_COMBO_PM_CH1                1085
#define IDC_EDIT_PM_WL2                 1086
#define IDC_EDIT_PM_IL2                 1087
#define IDC_COMBO_PM_CH2                1088
#define IDC_EDIT_PM_WL3                 1089
#define IDC_EDIT_PM_IL3                 1090
#define IDC_COMBO_PM_CH3                1091
#define IDC_EDIT_PM_WL4                 1092
#define IDC_EDIT_PM_IL4                 1093
#define IDC_COMBO_PM_CH4                1094
#define IDC_BUTTON_SINGLE_TEST          1095
#define IDC_EDIT_SINGLE_CHANNEL         1096
#define IDC_BUTTON_UP                   1097
#define IDC_EDIT_RL1                    1101
#define IDC_EDIT_RL2                    1102
#define IDC_EDIT_RL3                    1103
#define IDC_BUTTON_CHECK                1103
#define IDC_EDIT_RL4                    1104
#define IDC_BUTTON_LIGHT                1104
#define IDC_EDIT_RL5                    1105
#define IDC_EDIT_LIGHT_COM              1105
#define IDC_EDIT_RL6                    1106
#define IDC_EDIT_RL7                    1107
#define IDC_COMBO_LIGHT_CH              1107
#define IDC_EDIT_RL8                    1108
#define IDC_EDIT_RL9                    1109
#define IDC_EDIT_RL10                   1110
#define IDC_STATIC_COMPORT              1110
#define IDC_EDIT_RL11                   1111
#define IDC_STATIC_COMPORT2             1111
#define IDC_EDIT_RL12                   1112
#define IDC_EDIT_RL13                   1113
#define IDC_CHECK1                      1113
#define IDC_EDIT_RL14                   1114
#define IDC_EDIT_RL15                   1115
#define IDC_EDIT_RL16                   1116
#define IDC_EDIT_RL17                   1117
#define IDC_EDIT_RL18                   1118
#define IDC_EDIT_RL19                   1119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
