#if !defined(AFX_OP8169_H__4DCB5D06_6C9C_4EA0_8D46_182D058670BA__INCLUDED_)
#define AFX_OP8169_H__4DCB5D06_6C9C_4EA0_8D46_182D058670BA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COp8169 wrapper class

class COp8169 : public CWnd
{
protected:
	DECLARE_DYNCREATE(COp8169)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd261c586, 0x6f99, 0x11d5, { 0x95, 0x9, 0x0, 0xb0, 0xd0, 0x16, 0xad, 0x46 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetDeviceAddress();
	void SetDeviceAddress(long);
	long GetDelayMilSecs();
	void SetDelayMilSecs(long);

// Operations
public:
	BOOL OpenDevice();
	void CloseDevice();
	BOOL GetCurrentPOSPolarizer(double* alpha);
	BOOL SetALL(double alphaP, double alphaQ, double alphaH);
	BOOL SetPOSPolarizer(double alpha);
	BOOL SetPOSQuarter(double alpha);
	BOOL SetPOSHalf(double alpha);
	BOOL SetHorizontalAngles(double AlphaPMax, double Wavelength);
	BOOL SetVerticalAngles(double AlphaPMax, double Wavelength);
	BOOL SetDiagonalAngles(double AlphaPMax, double Wavelength);
	BOOL SetRightHandCircularAngles(double AlphaPMax, double Wavelength);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OP8169_H__4DCB5D06_6C9C_4EA0_8D46_182D058670BA__INCLUDED_)
